require_relative 'base'
require_relative 'files_controller'
require_relative 'folder_controller'
require_relative 'accounts/authentication_controller'
require_relative 'accounts/accounts_controller'
require_relative 'record/records_controller'
require_relative 'keyword_controller'
